### ISSUE TITLE
Checkpoint key error when finetuning

### ISSUE THREAD

**Issue by abelghazinyan** [bryandlee/FreezeG#5]
I have converted stylegan2-ffhq-config-f.pkl from official repo to stylegan2-ffhq-config-f.pt using convert_weight.py, then converted my dataset with prepare_data.py.

After that I am running this command: `python train.py --finetune_loc 2 --ckpt stylegan2-ffhq-config-f.pt ./data_processed/
`to finetune on my dataset but getting error:

`load model: stylegan2-ffhq-config-f.pt
Traceback (most recent call last):
  File "train.py", line 439, in <module>
    generator.load_state_dict(ckpt["g"], strict=False)
KeyError: 'g'`

**Comment by bryandlee** [comment]
Hi, the flags --gen and --disc are needed for the conversion.

https://github.com/bryandlee/FreezeG/blob/3b84a47eb190fc21ba13d5e26460e73a4a2af00b/stylegan2/convert_weight.py#L205-L206

Also, if you want to finetune from the converted checkpoint then you might need to convert the optimizer parameters as well.
Check out the issue from the original repo: https://github.com/rosinality/stylegan2-pytorch/issues/105

**Comment by abelghazinyan** [comment]
Hi, I have converted the weights with `--gen` and `--disc`, but still getting an error:

`load model: stylegan2-ffhq-config-f.pt
Traceback (most recent call last):
  File "train.py", line 444, in <module>
    g_optim.load_state_dict(ckpt["g_optim"])
KeyError: 'g_optim'`

Have you managed to finetune on 1024x1024 model?

**Comment by bryandlee** [comment]
To finetune from the converted model, the optimizer variables should be converted as well. Or you could simply comment out the optimizer loading part.

**Comment by abelghazinyan** [comment]
Hi I have commented out the optimizer loading part and that error passed.
But I am having new problems.
whenever I try to train on 1024x1024 images with batch size of 1 I am getting cuda out of memory error. I am using V100 16gb GPU. Then I tried on a machine with 4 V100s with distributed training, still getting out of memory error.
the error is like this:

`load model: stylegan2-ffhq-config-f.pt
d: 0.6701; g: 1.7785; r1: 0.0147; path: 0.0000; mean path: 0.0000; augment: 0.0000:   0%|                                                                                  | 0/800000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 335, in train
    sample, _ = g_ema([sample_z])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/stylegan2_tmp/model.py", line 542, in forward
    out = conv1(out, latent[:, i], noise=noise1)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/stylegan2_tmp/model.py", line 336, in forward
    out = self.conv(input, style)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/stylegan2_tmp/model.py", line 258, in forward
    out = F.conv_transpose2d(input, weight, padding=0, stride=2, groups=batch)
RuntimeError: CUDA out of memory. Tried to allocate 8.02 GiB (GPU 0; 15.78 GiB total capacity; 12.93 GiB already allocated; 874.00 MiB free; 13.70 GiB reserved in total by PyTorch)
d: 0.6701; g: 1.7785; r1: 0.0147; path: 0.0000; mean path: 0.0000; augment: 0.0000:   0%|                                                                                  | 0/800000 [00:02<?, ?it/s]`

But my goal is to finetune on the stylegan2-ffhq-config-f.pt model with my 1024x1024 dataset. When I try on one GPU I get same out of memory error. So I tried to do it on 4 gpus.
this is the command: `python -m torch.distributed.launch --nproc_per_node=4 train.py --finetune_loc 2 --size 1024 --ckpt stylegan2-ffhq-config-f.pt --batch 1 lmdb/real_1024`

I have tried with batch size 4 also, but getting this error: 

`Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
load model: stylegan2-ffhq-config-f.pt
load model: stylegan2-ffhq-config-f.pt
load model: stylegan2-ffhq-config-f.pt
load model: stylegan2-ffhq-config-f.pt
  0%|                                                                                                                                                                      | 0/800000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 178, in train
    requires_grad(generator, False, target_layer=f'convs.{generator.num_layers-2-2*loc}')
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'num_layers'
Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 178, in train
    requires_grad(generator, False, target_layer=f'convs.{generator.num_layers-2-2*loc}')
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'num_layers'
Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 178, in train
    requires_grad(generator, False, target_layer=f'convs.{generator.num_layers-2-2*loc}')
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'num_layers'
Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 178, in train
    requires_grad(generator, False, target_layer=f'convs.{generator.num_layers-2-2*loc}')
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'num_layers'
  0%|                                                                                                                                                                      | 0/800000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch_p36/bin/python', '-u', 'train.py', '--local_rank=3', '--finetune_loc', '2', '--size', '1024', '--ckpt', 'stylegan2-ffhq-config-f.pt', '--batch', '1', 'lmdb/real_1024']' returned non-zero exit status 1.`

I have tried to train with the tensorflow implementation and even with one gpu I am not getting memory error, but my goal is to use your finetuning.
Thanks for the great repo!

**Comment by bryandlee** [comment]
Hi, I haven't managed to train the 1024 model either. I guess the pytorch implementation of StyleGAN2 takes more gpu memories than the original one?
